### ISSUE TITLE
Feature Request: Track progress of tor bootstrapping

### ISSUE THREAD

**Issue by mattcollier** [Mowje/node-ths#7]
I have observed that tor bootstrapping can sometimes take 15-30 seconds (a long time).  My app can't do anything until tor is ready.

I have also observed that tor give bootstrapping progress on the command line which is being monitored by ths.

Some mechanism for monitoring or notification regarding the bootstrapping would be great.

**Comment by abenmrad** [comment]
Alright. I've been adding events to the `ths` object. 3 events will be made available: `bootstrap`, `bootstrapped` and `stop`

Hasn't been documented yet, nor applied to `ths_pool`. You can see the work in the [dev](https://github.com/Mowje/node-ths/compare/dev) branch.

**Comment by mattcollier** [comment]
Just implemented the bootstrap emitter in my code.  Works great!
